repositories:
  - name: bitnami-labs
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: smallstep
    url: https://smallstep.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: percona
    url: https://percona.github.io/percona-helm-charts/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: sloth
    url: https://slok.github.io/sloth
  - name: aqua
    url: https://aquasecurity.github.io/helm-charts/
  - name: arc
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true
  - name: actions-runner-controller-legacy
    url: https://actions-runner-controller.github.io/actions-runner-controller
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts/

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'
  nestedChart: &nestedChart
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'
          - --nested-chart
          - "true"

releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: 1.8.3
    <<: *defaults

  - name: sealed-secrets
    chart: bitnami-labs/sealed-secrets
    version: 2.17.9
    <<: *defaults

  - name: grafana-operator
    chart: grafana/grafana-operator
    version: 5.21.1
    <<: *defaults

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 1.17.1
    <<: *defaults

  - name: istio-base
    chart: istio/base
    version: 1.28.1
    <<: *defaults

  - name: step-issuer
    chart: smallstep/step-issuer
    version: 1.9.11
    <<: *defaults

  - name: mimir-distributed
    chart: grafana/mimir-distributed
    version: 5.8.0
    <<: *defaults

  - name: tempo-distributed
    chart: grafana/tempo-distributed
    version: 1.58.1
    <<: *defaults

  - name: grafana-agent-operator
    chart: grafana/grafana-agent-operator
    version: 0.5.2
    <<: *defaults

  - name: pg-db
    chart: percona/pg-db
    version: 2.8.1
    <<: *defaults

  - name: pg-operator
    chart: percona/pg-operator
    version: 2.8.1
    <<: *defaults

  - name: psmdb-db
    chart: percona/psmdb-db
    version: 1.20.1
    <<: *defaults

  - name: pxc-db
    chart: percona/pxc-db
    version: 1.18.0
    <<: *defaults

  - name: cloudnative-pg
    chart: cnpg/cloudnative-pg
    version: 0.26.0
    <<: *defaults

  - name: sloth
    chart: sloth/sloth
    version: 0.15.0
    <<: *defaults

  - name: trivy-operator
    chart: aqua/trivy-operator
    version: 0.31.0
    <<: *defaults

  - name: gha-runner-scale-set-controller
    chart: arc/gha-runner-scale-set-controller
    version: 0.13.0
    <<: *defaults

  - name: actions-runner-controller-legacy
    chart: actions-runner-controller-legacy/actions-runner-controller
    version: 0.23.7
    <<: *defaults

  - name: grafana-alloy
    chart: grafana/alloy
    version: 1.5.1
    <<: *nestedChart

  - name: nack
    chart: nats/nack
    version: 0.31.1
    <<: *defaults


    
