repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts/

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'

releases:
  - name: nack
    chart: nats/nack
    version: 0.35.0
    <<: *defaults

    
