repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: bitnami-labs
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: traefik
    url:  https://helm.traefik.io/traefik
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: smallstep
    url: https://smallstep.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: percona
    url: https://percona.github.io/percona-helm-charts/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: sloth
    url: https://slok.github.io/sloth
  - name: aqua
    url: https://aquasecurity.github.io/helm-charts/
  - name: arc
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'

releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: 0.37.0
    <<: *defaults

  - name: sealed-secrets
    chart: bitnami-labs/sealed-secrets
    version: 2.15.4
    <<: *defaults

  - name: kube-prometheus
    chart: bitnami/kube-prometheus
    version: 9.5.0
    <<: *defaults

  - name: grafana-operator
    chart: bitnami/grafana-operator
    version: 4.4.5
    <<: *defaults

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 1.8.1
    <<: *defaults

  - name: traefik
    chart: traefik/traefik
    version: 28.0.0
    <<: *defaults

  - name: istio-base
    chart: istio/base
    version: 1.22.1
    <<: *defaults

  - name: step-issuer
    chart: smallstep/step-issuer
    version: 1.9.1
    <<: *defaults

  - name: mimir-distributed
    chart: grafana/mimir-distributed
    version: 5.3.0
    <<: *defaults

  - name: tempo-distributed
    chart: grafana/tempo-distributed
    version: 1.11.0
    <<: *defaults

  - name: grafana-agent-operator
    chart: grafana/grafana-agent-operator
    version: 0.4.0
    <<: *defaults

  - name: pg-db
    chart: percona/pg-db
    version: 2.3.18
    <<: *defaults

  - name: pg-operator
    chart: percona/pg-operator
    version: 2.3.4
    <<: *defaults

  - name: ps-db
    chart: percona/ps-db
    version: 0.7.0
    <<: *defaults

  - name: psmdb-db
    chart: percona/psmdb-db
    version: 1.16.1
    <<: *defaults

  - name: pxc-db
    chart: percona/pxc-db
    version: 1.14.3
    <<: *defaults

  - name: cloudnative-pg
    chart: cnpg/cloudnative-pg
    version: 0.21.2
    <<: *defaults

  - name: sloth
    chart: sloth/sloth
    version: 0.7.0
    <<: *defaults

  - name: trivy-operator
    chart: aqua/trivy-operator
    version: 0.23.3
    <<: *defaults

  - name: arc
    chart: arc/gha-runner-scale-set-controller
    version: 0.9.2
    <<: *defaults
