repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: bitnami-labs
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: cilium
    url: https://helm.cilium.io/
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: teleport
    url: https://charts.releases.teleport.dev
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'

releases:

  - name: karpenter
    chart: karpenter/karpenter
    version: v0.22.0
    <<: *defaults
  
  - name: sealed-secrets
    chart: bitnami-labs/sealed-secrets
    version: 2.7.3
    <<: *defaults

  - name: kube-prometheus
    chart: bitnami/kube-prometheus
    version: 8.3.2
    <<: *defaults

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 1.4.7
    <<: *defaults