repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: bitnami-labs
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: traefik
    url:  https://helm.traefik.io/traefik
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: smallstep
    url: https://smallstep.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: percona
    url: https://percona.github.io/percona-helm-charts/
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: sloth
    url: https://slok.github.io/sloth
  - name: aqua
    url: https://aquasecurity.github.io/helm-charts/
  - name: arc
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true
  - name: actions-runner-controller-legacy
    url: https://actions-runner-controller.github.io/actions-runner-controller

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'
  nestedChart: &nestedChart
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'
          - --nested-chart
          - "true"

releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: 1.4.0
    <<: *defaults

  - name: sealed-secrets
    chart: bitnami-labs/sealed-secrets
    version: 2.17.2
    <<: *defaults

  - name: kube-prometheus
    chart: bitnami/kube-prometheus
    version: 11.1.14
    <<: *defaults

  - name: grafana-operator
    chart: bitnami/grafana-operator
    version: 4.9.17
    <<: *defaults

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 1.13.2
    <<: *defaults

  - name: traefik
    chart: traefik/traefik
    version: 35.2.0
    <<: *defaults

  - name: istio-base
    chart: istio/base
    version: 1.26.0
    <<: *defaults

  - name: step-issuer
    chart: smallstep/step-issuer
    version: 1.9.8
    <<: *defaults

  - name: mimir-distributed
    chart: grafana/mimir-distributed
    version: 5.7.0
    <<: *defaults

  - name: tempo-distributed
    chart: grafana/tempo-distributed
    version: 1.39.4
    <<: *defaults

  - name: grafana-agent-operator
    chart: grafana/grafana-agent-operator
    version: 0.5.1
    <<: *defaults

  - name: pg-db
    chart: percona/pg-db
    version: 2.6.0
    <<: *defaults

  - name: pg-operator
    chart: percona/pg-operator
    version: 2.6.0
    <<: *defaults

  - name: ps-db
    chart: percona/ps-db
    version: 0.9.0
    <<: *defaults

  - name: psmdb-db
    chart: percona/psmdb-db
    version: 1.19.1
    <<: *defaults

  - name: pxc-db
    chart: percona/pxc-db
    version: 1.17.0
    <<: *defaults

  - name: cloudnative-pg
    chart: cnpg/cloudnative-pg
    version: 0.23.2
    <<: *defaults

  - name: sloth
    chart: sloth/sloth
    version: 0.12.1
    <<: *defaults

  - name: trivy-operator
    chart: aqua/trivy-operator
    version: 0.28.1
    <<: *defaults

  - name: arc
    chart: arc/gha-runner-scale-set-controller
    version: 0.11.0
    <<: *defaults

  - name: actions-runner-controller-legacy
    chart: actions-runner-controller-legacy/actions-runner-controller
    version: 0.23.7
    <<: *defaults

  - name: grafana-alloy
    chart: grafana/alloy
    version: 1.0.3
    <<: *nestedChart
