repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: bitnami-labs
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: traefik
    url:  https://helm.traefik.io/traefik
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: smallstep
    url: https://smallstep.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

templates:
  defaults: &defaults
    hooks:
      - events:
          - prepare
        showlogs: true
        command: ./scripts/create-crd-chart.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --version
          - '{{`{{ .Release.Version }}`}}'
      - events:
          - cleanup
        showlogs: true
        command: ./scripts/copy-crds.py
        args:
          - --chart
          - '{{`{{ .Release.Chart }}`}}'
          - --download-path
          - '{{ requiredEnv "DOWNLOAD_PATH" }}'

releases:
  - name: karpenter
    chart: karpenter/karpenter
    version: v0.23.0
    <<: *defaults
  
  - name: sealed-secrets
    chart: bitnami-labs/sealed-secrets
    version: 2.7.3
    <<: *defaults

  - name: kube-prometheus
    chart: bitnami/kube-prometheus
    version: 8.3.2
    <<: *defaults

  - name: grafana-operator
    chart: bitnami/grafana-operator
    version: 2.7.17
    <<: *defaults

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 1.4.7
    <<: *defaults

  - name: traefik
    chart: traefik/traefik
    version: 20.8.0
    <<: *defaults

  - name: istio-base
    chart: istio/base
    version: 1.16.2
    <<: *defaults
    
  - name: step-issuer
    chart: smallstep/step-issuer
    version: 0.6.7
    <<: *defaults

  - name: mimir-distributed
    chart: grafana/mimir-distributed
    version: 4.1.0-weekly.224
    <<: *defaults

  - name: tempo-distributed
    chart: grafana/tempo-distributed
    version: 1.0.1
    <<: *defaults
