name: Fetch and Release Charts

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - helmfile.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: "v0.150.0"
          helm-version: "v3.11.0"
          kubectl-version: "1.24.7"
          kubectl-release-date: "2022-10-31"

      - name: Create CRD charts
        env:
          DOWNLOAD_PATH: "work"
        run: |
          rm -rf charts
          helmfile repos
          for release in $(helmfile list --skip-charts --output json | jq -r '.[].name')
          do
            rm -rf ${DOWNLOAD_PATH}
            helmfile fetch --skip-deps --concurrency=1 -l name=${release} --output-dir ${DOWNLOAD_PATH} --output-dir-template ${DOWNLOAD_PATH} ; helmfile lint --skip-deps --concurrency=1 -l name=${release}
          done

      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_SKIP_EXISTING: "true"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
